### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by ChaunceyHoover** [Pazaz/TFT_2_ST7775#1]
0 comments, explanation points, and docs. 0/10 would not use. Do you even open source?

**Comment by Pazaz** [comment]
I'll put this under consideration and work on it immediately. Thank you for bringing it to my attention, and have a nice day.

**Comment by ChaunceyHoover** [comment]
no but I need this done by tomorrow for my intro to java class and this is the only driver I could find

**Comment by Pazaz** [comment]
Understandable, as middle school isn't easy. I'll have it improved for you by then.

**Comment by ChaunceyHoover** [comment]
thnx just ping me at 127.0.0.1 when you're done. I have a ping messenger program I made in Visual Assembly class and I'll just let it wait for ur ping because I got ur ip from GitHub
